<?php $controller = $block->getCustomUrl();
    echo $block->getButtonHtml();
 ?>
<script type="text/javascript">
require(['jquery'], function ($) {
    jQuery(document).ready(function() {
       	jQuery("#create_list_btn").click(function(){
       		jQuery(".field-err-msg").remove();
            jQuery('#catalog_msg').remove();
    		var listName = jQuery("#prime_data_connect_step2_new_list").val();
    		var userKey = jQuery("#prime_data_connect_Step1_user_api_key").val();
    		if(listName == ""){
    			jQuery("#prime_data_connect_step2_new_list").focus();
    			jQuery('#row_prime_data_connect_step2_new_list .value').append('<p class="field-err-msg" style="color:red">This field is required.</p>');
    			return false;
    		}else if(userKey == ""){
    			jQuery("#prime_data_connect_Step1_user_api_key").focus();
    			jQuery('#prime_data_connect_Step1_user_api_key .value').append('<p class="field-err-msg" style="color:red">This field is required.</p>');
    			return false;
    		}
    		jQuery.ajax({
	        	url: "<?php echo $block->getUrl('primedataconnect/actionajax/Createlist'); ?>",
	        	type: "POST",
	        	showLoader: true,
	        	data: {listName:listName,userKey:userKey},
	        	success: function(response){
                    var obj = jQuery.parseJSON(response);
                    var catalog_uuid = obj.catalog_uuid;
		            if(catalog_uuid == "Something went wrong."){
                        jQuery('#row_prime_data_connect_step2_create_list_button').append('<p id="catalog_msg">Catalog not create.check setting and try again.</p>');
		            }else{
		            	jQuery("#prime_data_connect_step2_new_list").val("");
                        jQuery("#prime_data_connect_step2_custom_dropdown").append(new Option(listName, catalog_uuid,true, true));
		            }
			    }
    		});
    	});
	});
});

 </script>
